language: bash
sudo: required
dist: trusty
group: stable
env: GROUP=stable
matrix:
  include:
  - group: deprecated
    env: GROUP=deprecated

install:
- ps auxww | grep h[a]v
script:
- sudo docker version
- sudo docker run busybox echo hai
