language: ruby

sudo: required

dist: trusty

group: edge

before_install:
- echo 'all.rvmrcs' >> $rvm_user_path/rvmrc_ignored
- echo 'allGemfiles' >> $rvm_user_path/rvmrc_ignored
- echo 'rvm use default' > .rvmrc
- cd .

script: echo whatever
