sudo: required
dist: trusty
language: ruby
rvm: 2.3.3
before_script:
- sudo apt-get update
- sudo apt-get install language-pack-sv
- sudo locale-gen --no-archive sv_SE.UTF-8
- sudo /etc/init.d/postgresql stop
- sudo rm -rf /var/lib/postgresql/9.6/main
- sudo find /etc/postgresql/ -name initdb
- sudo -u postgres -- /var/lib/postgresql/9.6/bin/initdb --locale=sv_SE.UTF-8 -D /var/lib/postgresql/9.6/main || echo nah
- sudo /etc/init.d/postgresql start 9.6
- psql -c 'create database travis_ci_test;' -U postgres
script:
- psql travis_ci_test -a -f schema.sql
- psql travis_ci_test -a -f alter.sql
- psql travis_ci_test -a -f inspect.sql
- psql travis_ci_test -a -f create_collation.sql
- psql travis_ci_test -a -f alter.sql
- psql travis_ci_test -a -f inspect.sql
