language: go
addons:
  apt:
    packages:
    - dnsutils
matrix:
  include:
  - sudo: false
    env: WUT=ec2
  - sudo: required
    env: WUT=gce
script:
- dig releases.hashicorp.com
- ping -c 5 releases.hashicorp.com
- curl --connect-timeout 5 -vvvv -sSL -O https://releases.hashicorp.com/packer/0.12.1/packer_0.12.1_linux_amd64.zip
