language: ruby
sudo: false
cache:
  bundler: true
notifications:
  email: false
addons:
  sauce_connect:
    username: meatballhat
    access_key:
      secure: kKhRinh57TsgNlLaKKfBf6UbI3pzScRG3sBlsVS4I8eUpIzFoNqcqoF8yE7srAPruAtSmXZ61IFBrnC40AMt2kVsr9CrfJntnU0BH+iDcgMlNvJxCjZGQ8Ait4xysbc+ZSGEOX7R4gLXQiW0E7ndN+UQ2vtM/4QoX17D5ibq+iU=
before_script:
- gem install rack
- rackup --port 8000 &
