language: __sugilite__
sudo: required
dist: trusty
group: stable
env: STACK=sugilite GROUP=stable PYTHONPATH="/usr/lib/python2.7/dist-packages:$PYTHONPATH"
install:
- sudo apt-add-repository -y 'deb http://www.apache.org/dist/cassandra/debian 39x main'
- curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
- sudo apt-get update -y
- sudo apt-get install -y cassandra cassandra-tools
- sudo service cassandra start
script:
- find /usr/lib /usr/local/lib -name cqlshlib
- cqlsh --version
- cqlsh --help
- cqlsh --debug -e quit
