sudo: required
dist: trusty
language: ruby
addons:
  postgresql: 9.6
before_script:
- sudo apt-get update
- sudo apt-get install language-pack-sv
- sudo locale-gen --no-archive sv_SE.UTF-8
- sudo apt-get remove postgresql-9.6
- sudo apt-get purge postgresql-9.6
- sudo rm -rf /var/lib/postgresql/9.6/main /etc/postgresql/9.6/main
- sudo apt-get install postgresql-9.6
- sudo /etc/init.d/postgresql start 9.6
- export PGPORT=5433
# - sudo /etc/init.d/postgresql stop
# - sudo rm -rf /etc/postgresql/9.6/main
# - sudo -u postgres HOME=/var/lib/postgresql bash -c '/usr/lib/postgresql/9.6/bin/initdb --locale=sv_SE.UTF-8 -D /etc/postgresql/9.6/main' || echo nah
# - sudo -u postgres HOME=/var/lib/postgresql bash -c '/usr/lib/postgresql/9.6/bin/pg_ctl -D /etc/postgresql/9.6/main -l /var/tmp/postgresql.log start' &
# - sleep 10
# - sudo -u postgres HOME=/var/lib/postgresql bash -c '/usr/lib/postgresql/9.6/bin/createuser -s -l travis'
# - sudo -u postgres HOME=/var/lib/postgresql bash -c '/usr/lib/postgresql/9.6/bin/createdb -O travis travis_ci_test'
- createuser -s -l travis -U postgres
- createdb -O travis travis_ci_test -U postgres
script:
- psql travis_ci_test -a -f schema.sql
- psql travis_ci_test -a -f alter.sql
- psql travis_ci_test -a -f inspect.sql
- psql travis_ci_test -a -f create_collation.sql
- psql travis_ci_test -a -f alter.sql
- psql travis_ci_test -a -f inspect.sql
