language: bash

sudo: required

dist: trusty

group: stable

matrix:
  include:
  - language: __sugilite__
  - language: __amethyst__
  - language: __garnet__
  - language: __connie__

install: echo nope

script:
- cat /etc/hosts
