language: go
sudo: false
install:
- mkdir -p "${HOME}/pgdata"
- redis-server --port 19876 &>>redis-server.log &
- (while true; do date -u ; sleep 1; done) &>>whattimeisit.log &
- find /usr/local -name postgres
# - postgres -D "${HOME}/pgdata" &>>postgres.log &
script:
- jobs
- ps auxww
- for l in *.log; do echo "---> $l"; cat $l; done
