language: python

sudo: required

dist: trusty

group: dev

install:
- source ~/.bashrc
- type rvm | head -1 || true
- source ~/.rvm/scripts/rvm || true
- type rvm | head -1 || true

script:
- rvm use default
