language: bash
sudo: false
env:
  global:
  - PATH=$HOME/bin:$PATH
cache:
  debug: true
  directories:
  - $HOME/.local/cache
install:
- mkdir -p $HOME/.local/cache
- "cd $HOME/.local/cache ;
  if [ ! -f packer_0.7.5_linux_amd64.zip ] ; then
    curl -sSLO -w \"
             time_namelookup:  %{time_namelookup} s
                time_connect:  %{time_connect} s
             time_appconnect:  %{time_appconnect} s
            time_pretransfer:  %{time_pretransfer} s
               time_redirect:  %{time_redirect} s
          time_starttransfer:  %{time_starttransfer} s
              speed_download:  %{speed_download} bytes/s
               url_effective:  %{url_effective}
                             ----------
                  time_total:  %{time_total} s\" https://dl.bintray.com/mitchellh/packer/packer_0.7.5_linux_amd64.zip ;
  fi ;
  if [ ! -f artifacts ] ; then
    curl -sSLO -w \"
             time_namelookup:  %{time_namelookup} s
                time_connect:  %{time_connect} s
             time_appconnect:  %{time_appconnect} s
            time_pretransfer:  %{time_pretransfer} s
               time_redirect:  %{time_redirect} s
          time_starttransfer:  %{time_starttransfer} s
              speed_download:  %{speed_download} bytes/s
               url_effective:  %{url_effective}
                             ----------
                  time_total:  %{time_total} s\" https://s3.amazonaws.com/meatballhat/artifacts/stable/build/linux/amd64/artifacts ;
    chmod +x artifacts
  fi"
- mkdir -p $HOME/bin
- cd $HOME/bin && unzip $HOME/.local/cache/packer_0.7.5_linux_amd64.zip && cp -v $HOME/.local/cache/artifacts $HOME/bin/artifacts
script:
- packer version
- artifacts --version
