language: bash

sudo: required

dist: trusty

group: dev

before_install:
- cat /etc/cloud/cloud.cfg || true

install:
- sudo apt-get update
- sudo apt-get install -y dnsutils

script: dig $(hostname)
