language: ruby
rvm: 2.4.0
matrix:
  include:
  - dist: trusty
    sudo: required
  - dist: trusty
    sudo: false
  - dist: precise
    sudo: required
  - dist: precise
    sudo: false
install: echo install
script: ruby -v
