language: clojure

sudo: required

dist: trusty

matrix:
  include:
  - group: edge
  - group: whatever

install: echo install lolol

script:
- echo $PATH
- which bzip2
- bzip2 --version 2>/dev/null
- sudo docker run busybox echo ohai
- echo $JAVA_HOME
- cat /etc/hosts
- ping -c 1 localhost
- ping -c 1 127.0.0.1
- python -m SimpleHTTPServer 19494 &>/dev/null &
- sleep 3
- curl -s 'http://localhost:19494/'
- echo GET / | nc localhost 19494
- python -c 'import socket;print socket.gethostname()'
- stat ~/.ssh
- stat ~/.ssh/authorized_keys
- stat ~/.ssh/known_hosts
