language: ruby

matrix:
  include:
  - sudo: required
    dist: trusty
    group: edge
  - sudo: false
  - sudo: required

before_install:
- if test -f ~/.bashrc ; then cat ~/.bashrc ; fi
- if test -f ~/.bash_profile ; then cat ~/.bash_profile ; fi
- if test -f ~/.rvmrc ; then cat ~/.rvmrc ; fi
# - echo 'all.rvmrcs' >> /usr/local/rvm/user/rvmrc_ignored
# - echo 'allGemfiles' >> /usr/local/rvm/user/rvmrc_ignored
# - echo 'rvm use default' > .rvmrc
# - cd .

script: echo whatever
