language: python
sudo: required
dist: trusty
services:
- mysql
install: echo nope
script:
- find /etc/init /etc/init.d -name 'mysql*' | while read -r f; do echo "---> $f"; cat $f; done
- mysql -V
- echo 'SHOW VARIABLES LIKE "%version%";' | mysql
- mysql -e 'create database myapp_test;'
- mysql -e "grant all on myapp_test.* to 'travis'@'%';"
- mysql -u travis myapp_test -e 'select "wat";'
