language: generic

sudo: required

dist: trusty

group: edge

install: echo install whatever

script:
- sudo apt-get update -y
- sudo apt-get purge -y vim
- sudo apt-get install -y vim-tiny
- hash -r
- which vim
- vim --version
- sudo apt-get install -y vim
- hash -r
- which vim
- vim --version
