language: java
jdk: oraclejdk8
install: true
script:
- java -version
- ls -l /usr/lib/jvm
- sudo rm -fv /usr/lib/jvm/default-java
- jdk_switcher use oraclejdk8
- ls -l /usr/lib/jvm
- java -version
- xvfb-run java -version
- sudo service elasticsearch stop || true
- sudo service elasticsearch start || true
matrix:
  include:
    - env: "image=sudo trusty stable"
      sudo: required
      dist: trusty
      group: stable
    - env: "image=sudo trusty edge"
      sudo: required
      dist: trusty
      group: edge
    - env: "image=sudo trusty deprecated"
      sudo: required
      dist: trusty
      group: deprecated
    - env: "image=sudo precise stable"
      sudo: required
      dist: precise
      group: stable
    - env: "image=sudo precise edge"
      sudo: required
      dist: precise
      group: edge
    - env: "image=sudo precise deprecated"
      sudo: required
      dist: precise
      group: deprecated
#     - env: "image=container trusty stable"
#       sudo: false
#       dist: trusty
#       group: stable
#     - env: "image=container trusty edge"
#       sudo: false
#       dist: trusty
#       group: edge
#     - env: "image=container precise stable"
#       sudo: false
#       dist: precise
#       group: stable
#     - env: "image=container precise edge"
#       sudo: false
#       dist: precise
#       group: edge
notifications:
  email: false
