language: bash
sudo: false
os:
- linux
- osx
env:
  matrix:
  - CODE=0
  - CODE=1
  - CODE=2
  - CODE=3
install:
- echo wait for it
- sleep 1
- ./exit-with $CODE
script:
- echo wait for it
- sleep 1
- ./exit-with $CODE
