language: go
go: 1
sudo: required
dist: trusty
group: edge
script:
- sudo apt update -y
- sudo apt search openjdk
- sudo apt remove -y openjdk-8-jdk
- sudo apt update -y
- sudo apt install -y openjdk-8-jdk
