language: __sugilite__

sudo: required

dist: trusty

env:
  global: STACK=sugilite

install: echo nope

script:
- find /etc/apt -name '*.list' | while read -r f ; do
    echo "---> $f:" ; cat "${f}" ;
  done
- curl -sSL -H 'Metadata-Flavor: Google'
    http://metadata.google.internal/computeMetadata/v1/instance/zone
