language: minimal
sudo: required
dist: trusty
group: stable

env:
- STACK=android
- STACK=erlang
- STACK=go
- STACK=haskell
- STACK=jvm
- STACK=nodejs
- STACK=perl
- STACK=php
- STACK=python
- STACK=ruby

install:
- test -n "${STACK}"
- git clone --branch=meat-precise-container-updates https://github.com/travis-ci/packer-templates.git
script:
- cd packer-templates/dockerfiles/travisci/travis-${STACK}
- docker build -t travisci/travis-${STACK}:2017Q1 . &&
  cd ../../../ &&
  DOCKER_DEST=travisci/travis-${STACK}:2017Q1 ./bin/docker-push
