language: go
services:
- redis-server
go:
- 1
sudo: false
dist: trusty
before_install:
- find /etc/init -name '*redis*'
- cat /etc/init/redis-server.conf
- dmesg | grep -i redis
after_success:
- go run ./whatever.go
