language: generic

sudo: required

dist: trusty

group: edge

install: echo install whatever

script:
- sudo apt-get update -yqq
- dpkg -l
- dpkg-query -f '${Status}' -W bsdmainutils ; echo
- dpkg-query -f '${Status}' -W bsdmainutils | grep -E '^(install|hold) ok installed$'
- dpkg-query -f '${Status}' -W ncurses-dev ; echo
- dpkg-query -f '${Status}' -W ncurses-dev | grep -E '^(install|hold) ok installed$'
- dpkg-query -f '${Status}' -W libcurl4-gnutls-dev ; echo
- dpkg-query -f '${Status}' -W libcurl4-gnutls-dev | grep -E '^(install|hold) ok installed$'
- dpkg-query -f '${Status}' -W libldap-2.4-2 ; echo
- dpkg-query -f '${Status}' -W libldap-2.4-2 | grep -E '^(install|hold) ok installed$'
