language: bash

sudo: required

dist: precise

group: dev

before_install:
- cat /etc/cloud/cloud.cfg || true

install: sudo apt-get install -y dnsutils

script:
- hostname
- dig $(hostname)
- cat /etc/hosts
