language: go
go: 1
sudo: false
dist: trusty
addons:
  postgresql: '9.6'
services:
- redis-server
script:
- redis-cli INFO
- psql --version
- psql -c 'select version();' </dev/null
after_success:
- go run ./whatever.go
