sudo: required
dist: trusty
language: ruby
addons:
  postgresql: 9.6
before_script:
- sudo apt-get update
- sudo apt-get install language-pack-sv
- sudo locale-gen --no-archive sv_SE.UTF-8
- sudo apt-get remove postgresql-9.6
- sudo apt-get purge postgresql-9.6
- sudo rm -rf /var/lib/postgresql/9.6/main /etc/postgresql/9.6/main
- sudo apt-get install postgresql-9.6
- sudo /etc/init.d/postgresql start 9.6
- export PGPORT=5433
- sudo -u postgres -- createuser -s -l travis -U postgres
- sudo -u postgres -- createdb -O travis travis_ci_test -U postgres
script:
- psql travis_ci_test -a -f schema.sql
- psql travis_ci_test -a -f alter.sql
- psql travis_ci_test -a -f inspect.sql
- psql travis_ci_test -a -f create_collation.sql
- psql travis_ci_test -a -f alter.sql
- psql travis_ci_test -a -f inspect.sql
