language: ruby

sudo: required

dist: precise

install:
- sudo apt-get update -yqq
- sudo apt-get install -y postgresql-9.5-server

script:
- psql -l
- cat /etc/postgresql/9.5/main/postgresql.conf
- cat /etc/postgresql/9.5/main/postgresql.conf | bzip2 | base64
