language: ruby

sudo: required

dist: trusty

group: edge

matrix:
  include:
  - dist: precise
    language: ruby
    group: edge

script:
- mvn 'help:describe' -Dplugin=help 2>maven.err 1>maven.out
