language: ruby

sudo: required

dist: trusty

group: edge

install: echo install whatever

script:
- which python || true
- python -V || true
- which python2 || true
- python2 -V || true
- which python3 || true
- python3 -V || true
