language: generic

sudo: required

dist: trusty

group: edge

install: echo install whatever

script:
- sudo apt-get update -yqq
- sudo apt-get purge -yq vim
- sudo apt-get install -yq vim-tiny
- hash -r
- which vim
- which vi
- vim --version
- vi --version
- sudo apt-get install -yq vim
- hash -r
- which vim
- which vi
- vim --version
- vi --version
