language: generic

dist: trusty

group: edge

install: echo whatever eh

script:
- sudo docker run busybox echo ohai
- echo $JAVA_HOME
- cat /etc/hosts
- ping -c 3 localhost
- ping -c 3 127.0.0.1
- host localhost
- host $(hostname)
- stat ~/.ssh
- stat ~/.ssh/authorized_keys
- stat ~/.ssh/known_hosts
