language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- pypy-2.6.1
- pypy-4.0.1
- pypy-5.1
sudo: false
dist: trusty
group: beta
install: echo nope
script:
- curl -vvvvLO https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-2.6.tar.bz2
- sha256sum python-2.6.tar.bz2
- tar -tjf python-2.6.tar.bz2
- curl -vvvvLO https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.4.tar.bz2
- sha256sum python-3.4.tar.bz2
- tar -tjf python-3.4.tar.bz2
- curl -vvvvLO https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/pypy-4.0.1.tar.bz2
- sha256sum pypy-4.0.1.tar.bz2
- tar -tjf pypy-4.0.1.tar.bz2
