language: generic
sudo: false
os:
- linux
- osx
addons:
  apt:
    sources:
    - chef-stable-precise
    - deadsnakes
    - unknown-source
    packages:
    - chefdk
    - python2.3
install: echo install
script: echo script
