language: go
sudo: false
env:
  matrix:
  - GIMME_ARCH=amd64
  - GIMME_ARCH=arm
  - GIMME_ARCH=386
os:
  - linux
  - osx
gobuild_args: -x -v
go:
- go1
- 1.4.1
- 1.4
- 1.2
- 1.2.1
- 1.3
- 1.3.3
- 1.0
- 1.0.3
- master
- tip
install: go get -x -v .
script: go test -x -v .
matrix:
  allow_failures:
  - env: GIMME_ARCH=arm
  - env: GIMME_ARCH=386
