language: __sugilite__

sudo: required
dist: trusty
group: dev

matrix:
  include:
  - language: __sugilite__
    dist: trusty
    env: STACK=sugilite
  - language: __connie__
    dist: trusty
    env: STACK=connie
  - language: __amethyst__
    dist: trusty
    env: STACK=amethyst
  - language: __garnet__
    dist: trusty
    env: STACK=garnet
  - language: android
    dist: precise
    env: STACK=android
  - language: erlang
    dist: precise
    env: STACK=erlang
  - language: go
    dist: precise
    env: STACK=go
  - language: haskell
    dist: precise
    env: STACK=haskell
  - language: jvm
    dist: precise
    env: STACK=jvm
  - language: nodejs
    dist: precise
    env: STACK=nodejs
  - language: perl
    dist: precise
    env: STACK=perl
  - language: php
    dist: precise
    env: STACK=php
  - language: python
    dist: precise
    env: STACK=python
  - language: ruby
    dist: precise
    env: STACK=ruby

install: echo nope
script:
- find /usr/bin /usr/local/bin -name git
- which git
- git --version
