language: python
sudo: false
matrix:
  include:
  - language: ruby
    ruby: 2.2.1
    sudo: required
    env:
    - A=1 B=2 C=3
    - D=4 E=5 F=6
  - python: "2.7"
    dist: trusty
    sudo: required
    env: A=2 B=3 C=1
  - language: go
    os: osx
    go: 1.4.2
    env: A=3 B=1 C=2
script:
- echo "A=$A B=$B C=$C"
- echo "$TRAVIS_PYTHON_VERSION"
