language: go
matrix:
  include:
  - dist: trusty
    sudo: required
    group: maven-test
    env: Q=maven-test,sudo
  - dist: trusty
    sudo: false
    group: maven-test
    env: Q=maven-test,nosudo
  - dist: trusty
    sudo: required
    env: Q=stable,sudo
  - dist: trusty
    sudo: false
    env: Q=stable,nosudo
script: mvn -version
