language: ruby

sudo: required

services:
- riak

install: echo install

script:
- riak version
- sudo riak ping
- sudo riak-admin test
- sleep 10
- sudo riak-admin test
- sleep 10
- sudo riak-admin test
