language: ruby

sudo: required

dist: trusty

group: edge

script:
- sudo apt-get update -yqq
- sudo apt-get purge -o Dpkg::Options::="--force-confnew" -yqq docker-engine
- sudo apt-get install -o Dpkg::Options::="--force-confnew" -yqq docker-engine lvm2 xfsprogs
- echo 'DOCKER_OPTS="$DOCKER_OPTS --storage-driver devicemapper"' | sudo tee -a /etc/default/docker
- sudo service docker restart
- docker run --rm -it --storage-opt size=11G ubuntu:14.04 df -h
