language: python
sudo: required
dist: trusty
group: dev
python: 3.4
install: echo nope
script:
- echo "PATH=$PATH"
- echo "$PATH" | if grep '::' ;then
    echo DOUBLE COLON WHAT DOES IT MEAN;
  else
    echo nah;
  fi
- ls -l /etc/profile.d/pyenv.sh
- cat /etc/profile.d/pyenv.sh
- pyenv versions
