language: java
sudo: required
jdk: oraclejdk7
script:
- echo "${PATH}" | tr ':' '\n'
- grep -l JAVA_HOME /etc/profile.d/* || true
- which java
- java -version
- echo $JAVA_HOME
- type jdk_switcher | head -1
- ls -la ~/ | grep jdk || true
- ls -la /opt | grep jdk || true
