language: python

sudo: required

dist: trusty

group: dev

install:
- cat ~/.bashrc || true
- source ~/.bashrc || true
- type rvm | head -1 || true
- cat ~/.rvm/scripts/rvm || true
- source ~/.rvm/scripts/rvm || true
- type rvm | head -1 || true

script:
- rvm use default
