language: python

sudo: required

group: edge

dist: precise

matrix:
  include:
  - dist: trusty
    language: universe

install: echo nope

script:
- sudo service mongod start
- sudo service mongod stop
