language: ruby

sudo: required

dist: trusty

group: edge

script:
- git clone --branch=meat-serverspec-combination
    'https://github.com/travis-ci/packer-templates.git'
- phantomjs packer-templates/cookbooks/lib/features/files/phantomjs_test_google.js
