language: python

sudo: required

group: edge

dist: precise

script:
- curl -L https://omnitruck.chef.io/install.sh | sudo bash
- ip addr
- ohai | grep ip6address
- sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
- sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
- ip addr
- ohai | grep ip6address
