language: ruby

sudo: required

dist: trusty

group: edge

script:
- sudo apt-get update -yqq
- sudo apt-get purge -o Dpkg::Options::="--force-confnew" -yqq docker-engine
- sudo apt-get install -o Dpkg::Options::="--force-confnew" -yqq docker-engine
- docker run --rm -it --storage-opt size=5G ubuntu:14.04 df -h
