language: __connie__

sudo: required
dist: trusty
group: edge

install: echo nope

script:
- sudo iptables -I INPUT 1 -p icmp -j ACCEPT
- sudo iptables -I INPUT 2 -p udp --dport '33434:33523' -j REJECT
- sudo iptables -I INPUT 3 -i lo -j ACCEPT
- sudo iptables -I INPUT 4 -m state --state 'ESTABLISHED,RELATED' -j ACCEPT
- sudo iptables -I INPUT 5 -p tcp --dport ssh -j ACCEPT
- sudo iptables -A INPUT -j DROP
- curl icanhazip.com
- ssh-import-id -o ~/.ssh/authorized_keys 'gh:meatballhat'
- while [[ ! -f /.die ]]; do echo -en '.'; sleep 30; done
