language: go
matrix:
  include:
  - dist: trusty
    sudo: required
    group: rebar3-test
    env: Q=rebar3-test,sudo
  - dist: trusty
    sudo: required
    env: Q=stable,sudo
script:
- rebar version || true
- rebar3 version || true
