language: java
sudo: required
jdk: oraclejdk7
script:
- echo "${PATH}" | tr ':' '\n'
- for f in $(grep -l JAVA_HOME /etc/profile.d/*); do echo "---> $f"; cat $f; done
- which java
- java -version
- echo $JAVA_HOME
- type jdk_switcher | head -1
- ls -la ~/ | grep jdk || true
- ls -la /opt | grep jdk || true
