language: __sugilite__

sudo: required

dist: trusty

env:
  global: STACK=sugilite

install: echo nope

script:
- find /etc/apt -name '*.list' | while read -r f ; do
    echo "---> $f:" ; cat "${f}" ;
  done
- docker run
    -e DOCKER_HOST_INFRA=gce
    -e APT_SOURCE_MUNGE_TO=mirror
    -v "${PWD}:/app" ubuntu:14.04 /app/apt-source-munge
