language: ruby

sudo: required

dist: trusty

group: edge

before_install:
# - rvm rvmrc warning ignore all.rvmrcs
# - echo 'rvm use default' > .rvmrc
# - cd .

script:
- find /usr/local/rvm -name db
- for f in $(find /usr/local/rvm -name db) ; do echo "$f --->" ; cat $f ; done
