language: ruby

sudo: required

dist: trusty

env:
  matrix:
  - OHAI=1
  global:
  - 'DISPLAY=:99.0'

group: edge

matrix:
  include:
  - dist: precise
    env: OHAI=2

script:
- sh -e /etc/init.d/xvfb start
- which xset
- DISPLAY=:99.0 xset -q
- sudo apt search xset
