language: ruby

sudo: false

services:
- cassandra

install: echo install

script:
- cqlsh --help 1>cqlsh-help.out 2>cqlsh-help.err
- cat cqlsh-help.out
- cat cqlsh-help.err
- cqlsh --version 1>cqlsh-version.out 2>cqlsh-version.err
- cat cqlsh-version.out
- cat cqlsh-version.err
- cqlsh --debug -e quit 1>cqlsh-debug-e-quit.out 2>cqlsh-debug-e-quit.err
- cat cqlsh-debug-e-quit.out
- cat cqlsh-debug-e-quit.err
- cqlsh --debug -e 'source "schema.cql"' 1>cqlsh-debug-e-source.out 2>cqlsh-debug-e-source.err
- cat cqlsh-debug-e-source.out
- cat cqlsh-debug-e-source.err
