language: ruby
dist: precise
sudo: required

install: echo install

script:
- curl -sSLO "http://ppa.launchpad.net/limparissoft/opencv-ppa/ubuntu/pool/main/o/opencv/opencv_2.4.5-0~3~precise1_amd64.deb"
- sudo dpkg -i "opencv_2.4.5-0~3~precise1_amd64.deb"
