language: go
go:
- 1
- 1.x
- 1.1.x
- 1.2.x
- 1.3.x
- 1.4.x
- 1.5.x
- 1.6.x
- 1.7.x
sudo: false
dist: trusty
env:
- HAI=0
- HAI=1
- HAI=2
- HAI=3
- HAI=4
- HAI=5
- HAI=6
- HAI=7
- HAI=8
- HAI=9
- HAI=10
- HAI=11
- HAI=12
- HAI=13
- HAI=14
- HAI=15
- HAI=16
- HAI=17
- HAI=18
- HAI=19
after_success:
- go run ./whatever.go
