language: perl
sudo: false
cache:
  directories:
  - $HOME/perl5/perlbrew/perls/perl-5.14.2
  - $HOME/.cpanm
before_install:
  - perlbrew list | grep -q 5.14.2 || (
      perlbrew install -v -j 2 perl-5.14.2 --as perl-5.14 --notest --noman --force 2>&1 |
        tee /tmp/perlbrew-install.log | sed 's/.*/\./' | tr "\n" " " ;
      perlbrew alias -f create 5.14 5.14.2 ;
      perlbrew use perl-5.14.2 ;
      for mod in ExtUtils::MakeMaker Dist::Zilla Moose Test::Pod Test::Pod::Coverage Test::Exception Dist::Zilla::Plugin::Bootstrap::lib LWP Module::Install Test::Most ; do
        cpanm ${mod} --force --notest || true ;
      done ;
    )
  - perlbrew use perl-5.14.2
  - perl --version
  - cpanm --version
  - find ~/perl5 -name perl -type f || true
install: echo not really
script: echo not really
