language: bash

sudo: required

dist: precise

group: dev

script:
- hostname
- ping -c 1 $(hostname)
- cat /etc/hosts
- cat /etc/cloud/templates/hosts.tmpl
- cat /etc/cloud/cloud.cfg || true
- for f in $(find /etc/cloud/cloud.cfg.d -type f) ; do
    echo "---> $f:" ;
    cat $f ;
  done
- for f in $(find /var/lib/cloud/seed -name '*-data' -type f) ; do
    echo "---> $f:" ;
    cat $f ;
  done
- for f in $(find /var/log -wholename '*cloud*' -type f) ; do
    echo "---> $f:" ;
    cat $f ;
  done
