language: bash
sudo: false
env:
  matrix:
  - BEFORE_INSTALL_CODE=1 INSTALL_CODE=0 BEFORE_SCRIPT_CODE=0 SCRIPT_CODE=0 AFTER_SCRIPT_CODE=0
  - BEFORE_INSTALL_CODE=0 INSTALL_CODE=1 BEFORE_SCRIPT_CODE=0 SCRIPT_CODE=0 AFTER_SCRIPT_CODE=0
  - BEFORE_INSTALL_CODE=0 INSTALL_CODE=0 BEFORE_SCRIPT_CODE=1 SCRIPT_CODE=0 AFTER_SCRIPT_CODE=0
  - BEFORE_INSTALL_CODE=0 INSTALL_CODE=0 BEFORE_SCRIPT_CODE=0 SCRIPT_CODE=1 AFTER_SCRIPT_CODE=0
  - BEFORE_INSTALL_CODE=0 INSTALL_CODE=0 BEFORE_SCRIPT_CODE=0 SCRIPT_CODE=0 AFTER_SCRIPT_CODE=1
  - BEFORE_INSTALL_CODE=2 INSTALL_CODE=0 BEFORE_SCRIPT_CODE=0 SCRIPT_CODE=0 AFTER_SCRIPT_CODE=0
  - BEFORE_INSTALL_CODE=0 INSTALL_CODE=2 BEFORE_SCRIPT_CODE=0 SCRIPT_CODE=0 AFTER_SCRIPT_CODE=0
  - BEFORE_INSTALL_CODE=0 INSTALL_CODE=0 BEFORE_SCRIPT_CODE=2 SCRIPT_CODE=0 AFTER_SCRIPT_CODE=0
  - BEFORE_INSTALL_CODE=0 INSTALL_CODE=0 BEFORE_SCRIPT_CODE=0 SCRIPT_CODE=2 AFTER_SCRIPT_CODE=0
  - BEFORE_INSTALL_CODE=0 INSTALL_CODE=0 BEFORE_SCRIPT_CODE=0 SCRIPT_CODE=0 AFTER_SCRIPT_CODE=2
  - BEFORE_INSTALL_CODE=3 INSTALL_CODE=0 BEFORE_SCRIPT_CODE=0 SCRIPT_CODE=0 AFTER_SCRIPT_CODE=0
  - BEFORE_INSTALL_CODE=0 INSTALL_CODE=3 BEFORE_SCRIPT_CODE=0 SCRIPT_CODE=0 AFTER_SCRIPT_CODE=0
  - BEFORE_INSTALL_CODE=0 INSTALL_CODE=0 BEFORE_SCRIPT_CODE=3 SCRIPT_CODE=0 AFTER_SCRIPT_CODE=0
  - BEFORE_INSTALL_CODE=0 INSTALL_CODE=0 BEFORE_SCRIPT_CODE=0 SCRIPT_CODE=3 AFTER_SCRIPT_CODE=0
  - BEFORE_INSTALL_CODE=0 INSTALL_CODE=0 BEFORE_SCRIPT_CODE=0 SCRIPT_CODE=0 AFTER_SCRIPT_CODE=3
before_install:
- ./exit-with $BEFORE_INSTALL_CODE
install:
- ./exit-with $INSTALL_CODE
before_script:
- ./exit-with $BEFORE_SCRIPT_CODE
script:
- ./exit-with $SCRIPT_CODE
after_script:
- ./exit-with $AFTER_SCRIPT_CODE
