language: python
sudo: required
dist: trusty
services:
- mysql
install: echo nope
script:
- mysql -V
- echo 'SHOW VARIABLES LIKE "%version%";' | mysql
- mysql -e 'create database myapp_test;'
- mysql -e "grant all on myapp_test.* to 'travis'@'%';"
- mysql -u travis myapp_test -e 'select "wat";'
