language: go
sudo: false
dist: trusty
install:
- /usr/lib/postgresql/9.3/bin/pg_ctl init -D "${HOME}/pgdata"
- redis-server --port 16379 &>>redis-server.log &
- (while true; do date -u ; sleep 1; done) &>>whattimeisit.log &
- /usr/lib/postgresql/9.3/bin/postgres -p 15432 -D "${HOME}/pgdata" &>>postgres.log &
script:
- jobs
- ps auxww
- for l in *.log; do echo "---> $l"; cat $l; done
