language: generic

sudo: required

dist: trusty

group: edge

script:
- sudo stop docker ;
  sudo cat /etc/default/docker ;
  echo 'DOCKER_OPTS="$DOCKER_OPTS --storage-opt dm.basesize=20G"' | sudo tee -a /etc/default/docker ;
  sudo cat /etc/default/docker ;
  sudo start docker ;
  sleep 5 ;
  sudo docker version
- docker run -d 'ubuntu-upstart:14.04' /sbin/init > .container-name
- docker inspect $(cat .container-name)
- docker exec -it $(cat .container-name) df -h
