language: node_js
node_js: 6.10.0
sudo: required
dist: precise
addons:
  apt:
    packages:
    - oracle-java8-installer
    - oracle-java8-set-default
install:
- curl -sSL -o /var/tmp/jdk_switcher.sh 'https://raw.githubusercontent.com/michaelklishin/jdk_switcher/master/jdk_switcher.sh'
script:
- source /var/tmp/jdk_switcher.sh
- jdk_switcher home oraclejdk8
- jdk_switcher use oraclejdk8
- java -version
- javac Huh.java
- java Huh
