language: python

sudo: required

dist: trusty

group: dev

install:
- set -x
- echo $HOME
- echo $PS1
- cat ~/.bashrc || true
- source ~/.bashrc || true
- type rvm | head -1 || true
- echo $HOME
- echo $PS1
- cat ~/.bash_profile || true
- source ~/.bash_profile || true
- type rvm | head -1 || true
- echo $HOME
- echo $PS1
- type rvm | head -1 || true
- cat ~/.rvm/scripts/rvm || true
- if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
    source "$HOME/.rvm/scripts/rvm" ;
    echo sourced ;
  else
    echo NOT SOURCED ;
  fi
- type rvm | head -1 || true

script:
- rvm use default
