language: ruby

sudo: required

dist: precise

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5

script:
- psql -l
- cat /etc/postgresql/9.5/main/postgresql.conf
- cat /etc/postgresql/9.5/main/postgresql.conf | bzip2 | base64
