language: php

sudo: required

php:
- 5.6.24
- 7.0.7

dist: trusty

env:
  global: STACK=sugilite

install: echo nope

script:
- pear version
- pear config-show
- cat /home/travis/.phpenv/versions/${TRAVIS_PHP_VERSION}/etc/pear.conf
- cat /home/travis/.pearrc
