language: perl
sudo: false
cache:
  directories:
  - $HOME/perl5/perlbrew/perls/perl-5.14.2
  - $HOME/.cpanm
before_install:
  - perlbrew list
  - perlbrew install perl-5.14.2 --as perl-5.14 --notest
  - perlbrew use perl-5.14
  - for mod in ExtUtils::MakeMaker Dist::Zilla Moose Test::Pod Test::Pod::Coverage Test::Exception Dist::Zilla::Plugin::Bootstrap::lib LWP Module::Install Test::Most ; do
      cpanm ${mod} --force --notest ;
    done
