language: java
dist: trusty
sudo: required
jdk: oraclejdk8

env:
  global:
  - PATH="$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH"

install:
- nvm install v6.10.0

script:
- node --version
- npm --version
- npm install bower grunt
- bower --version
- grunt --version
