language: bash
sudo: false

install: echo install
script: cat ~/.travis*

matrix:
  include:
  - language: android
  - language: erlang
  - language: go
  - language: haskell
  - language: jvm
  - language: node-js
  - language: perl
  - language: php
  - language: python
  - language: ruby
