language: node_js
node_js: 7
sudo: false
dist: precise
group: stable
install:
- echo nah
script:
- uptime
- curl -vvvv -SLO https://nodejs.org/dist/v7.7.3/node-v7.7.3-linux-x64.tar.xz
- file node-v7*
