language: __connie__

sudo: required
dist: trusty

matrix:
  include:
  - group: edge
    env: GROUP=edge
  - group: dev
    env: GROUP=dev
  - group: stable
    env: GROUP=stable

install: echo nope

script:
- sudo iptables -L
