language: __sugilite__

rvm: 2.2.2

sudo: required
dist: trusty
group: stable
env: STACK=sugilite GROUP=stable
services:
- mysqld

addons:
  firefox: 5.0.1
  apt:
    packages:
    - wkhtmltopdf


matrix:
  include:
  - language: __sugilite__
    dist: trusty
    group: edge
    env: STACK=sugilite GROUP=edge
  - language: __sugilite__
    dist: trusty
    group: deprecated
    env: STACK=sugilite GROUP=deprecated

install: echo nah
script:
- which mysql
- mysql --version
- echo 'SHOW VARIABLES LIKE "%version%"' | mysql
- sudo find /var/log -type f -name '*mysql*' | while read -r filename; do
    echo "---> ${filename}";
    sudo tail -1000 "${filename}";
  done
