#!/usr/bin/env bash
set -o errexit

main() {
  : "${BASEDIR:=/}"
  __intersection \
    <(__checksum_everything "${BASEDIR}") \
    <(sleep 10 && __checksum_everything "${BASEDIR}") \
    | sort -k 2
}

__checksum_everything() {
  local base="${1}"
  local sha256sum="${SHA256SUM:-sha256sum}"
  : "${base:=/}"
  find "${base}" -not -wholename '*/.git/*' -type f -print0 \
    | xargs -n 50 -0 "${sha256sum}" \
    | sort -k 2 \
    | uniq
}

__intersection() {
  ./lines-intersection "${1}" "${2}"
}

main "$@"
