#!/usr/bin/env bash
set -o errexit

main() {
  : "${DIRS:=/home,/usr,/lib,/etc}"
  __intersection \
    <(__checksum_everything ${DIRS//,/ }) \
    <(sleep 10 && __checksum_everything ${DIRS//,/ }) \
    | sort -k 2
}

__checksum_everything() {
  local sha256sum="${SHA256SUM:-sha256sum}"
  find "${@}" -not -wholename '*.git/*' -type f -print0 \
    | xargs -P 0 -n 50 -0 "${sha256sum}" \
    | sort -k 2 \
    | uniq
}

__intersection() {
  ./lines-intersection "${1}" "${2}"
}

main "$@"
