#!/usr/bin/env bash

set -o xtrace

if grep -q 'us-central1\.gce\.archive' /etc/apt/sources.list ; then
  sudo sed -i \
    's/us-central1\.gce\.archive/us-central1.gce.clouds.archive/' \
    /etc/apt/sources.list
  sudo apt-get update
fi
