source 'https://rubygems.org'

gem 'sqlite3'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '>= 2.2'
gem 'ace-rails-ap', '~> 3.0.3'
gem 'analytics-ruby', '>= 2.0.0', require: 'segment/analytics'
gem 'angular-rails-templates', '~> 1.0.0'
gem 'ar-octopus'
gem 'aws-kclrb'
gem 'aws-sdk-core'
gem 'bcrypt'
gem 'bootstrap-sass'
gem 'bourbon'
gem 'capybara'
gem 'cocoon'
gem 'coffee-rails', '>= 4.1.0'
gem 'compass-rails'
gem 'font-awesome-sass'
gem 'geocoder'
gem 'global_phone'
gem 'hologram'
gem 'http_accept_language'
gem 'koala'
gem 'less-rails'
gem 'maxminddb'
gem 'mini_magick'
gem 'mixpanel-ruby'
gem 'multi_json'
gem 'mysql2'
gem 'newrelic_rpm'
gem 'nexmo'
gem 'nokogiri'
gem 'oneapi-ruby'
gem 'paranoia', '>= 2.0'
gem 'pg'
gem 'rack-attack'
gem 'rails', '~> 4.2.1'
gem 'rake'
gem 'ransack'
gem 'redis'
gem 'rest-client'
gem 'retriable'
gem 'rollbar', '~> 2.11.5'
gem 'rubyzip'
gem 'sass-rails', '~> 5.0'
gem 'select2-rails'
gem 'sprockets', '= 3.6.3'
gem 'sucker_punch', '= 2.0.1'
gem 'thin'
gem 'timecop'
gem 'twilio-ruby'
gem 'twitter-bootstrap-rails', '2.2.8'
gem 'uglifier', '>= 2.7.1'
gem 'user_agent_parser'
gem 'will_paginate'
gem 'dogstatsd-ruby'
gem 'holidays'

source 'https://rails-assets.org' do
  gem 'rails-assets-angular', '~> 1.5.7'
  gem 'rails-assets-angucomplete-alt'
  gem 'rails-assets-angular-animate', '~> 1.5.7'
  gem 'rails-assets-angular-bootstrap', '= 1.3.1'
  gem 'rails-assets-angular-drag-and-drop-lists'
  gem 'rails-assets-angular-minicolors', '~> 0.0.9'
  gem 'rails-assets-ngInfiniteScroll'
  gem 'rails-assets-angular-perfect-scrollbar'
  gem 'rails-assets-angular-resource', '~> 1.5.7'
  gem 'rails-assets-angular-strap'
  gem 'rails-assets-angular-socket-io'
  gem 'rails-assets-angular-ui-ace'
  gem 'rails-assets-angular-ui-router'
  gem 'rails-assets-angular-ui-switch'
  gem 'rails-assets-bootstrap-daterangepicker'
  gem 'rails-assets-clipboard'
  gem 'rails-assets-color-thief'
  gem 'rails-assets-highcharts', '4.2.0'
  gem 'rails-assets-highcharts-ng'
  gem 'rails-assets-keymaster'
  gem 'rails-assets-moment'
  gem 'rails-assets-ngDialog'
  gem 'rails-assets-ngtoast'
  gem 'rails-assets-ng-file-upload', '~> 12.0.4'
  gem 'rails-assets-spinkit'
  gem 'rails-assets-underscore.string'
  gem 'rails-assets-waypoints', '2.0.3'
  gem 'rails-assets-Justified-Gallery'
  gem 'rails-assets-ng-rollbar'
end

group :development, :test do
  gem 'annotate'
  gem 'byebug'
  gem 'factory_girl_rails', require: false
  gem 'jasmine'
  gem 'phantomjs'
  gem 'pry-byebug'
  gem 'rails-assets-angular-mocks', '~> 1.5.7'
  gem 'rubocop'
  gem 'rspec-rails', '>= 3.0'
  gem 'teaspoon-jasmine'
  gem 'webmock'
end

group :test do
  gem 'codecov', require: false
  gem 'simplecov', require: false
  gem 'simplecov-lcov', require: false
end
