#!/usr/bin/env python
import sys

def main():
    lines_a = open(sys.argv[1]).read().splitlines()
    lines_b = open(sys.argv[2]).read().splitlines()

    sys.stdout.write(
        '\n'.join(
            set(lines_b).intersection(set(lines_a))
        )
    )
    sys.stdout.write('\n')


if __name__ == '__main__':
    sys.exit(main())
